/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package helloworld;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Nihal gupta
 */
public class MainScreen extends javax.swing.JFrame {

    String cusername = null;
    DefaultTableModel model = null;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        Connection con;
        PreparedStatement ps;
        ImageIcon image = null;
//        try {
//            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lance?user=root&password=Deadpool616");
//            ps = con.prepareStatement("select image from new_table where imgae_id = 6;");
//            Object[][] table = {};
//            ResultSet rs = ps.executeQuery();
//            while (rs.next()) {
//                byte[] imagedata = rs.getBytes("image");
//                image = new ImageIcon(imagedata);
//            }
//        } catch (SQLException e) {
//
//        };
//        String[] columnNames = {
//            "Category", "Item", "Price", "Qty"
//        };
//        Object[][] data = {
//            {image, "item1", "price1", "qty1"},
//            {image, "item2", "price2", "qty2"},
//            {image, "item3", "price3", "qty3"},
//            {image, "item4", "price4", "qty4"},};
        model = new DefaultTableModel() {

//            private static final long serialVersionUID = 1L;
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            @Override
            public Class getColumnClass(int column) {
                return getValueAt(0, column).getClass();
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;//This causes all cells to be not editable
            }

        };
        model.addColumn("Category");
        model.addColumn("Item");
        model.addColumn("Price");
        model.addColumn("Qty");
        model.addColumn("id");
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lance?user=root&password=Deadpool616");
            CallableStatement sp = con.prepareCall("call GetProductData();");
            ResultSet rs= sp.executeQuery();
            while (rs.next()) {
                byte[] imagedata = rs.getBytes("smallimage");
                image = new ImageIcon(imagedata);
                model.addRow(new Object[]{image, rs.getString("pname"), rs.getInt("price"), rs.getInt("quantity"),rs.getInt("pid")});

            }
            con.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        
        initComponents();
        jTable1.setRowHeight(133);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        JTableHeader header = jTable1.getTableHeader();
        header.setDefaultRenderer(centerRenderer);
        jTable1.setDefaultRenderer(String.class, centerRenderer);
        jTable1.setDefaultRenderer(Integer.class, centerRenderer);
//        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();
        btn_feedback = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_logout.setText("Log-out");
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });

        btn_feedback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_feedback.setText("Feedback");
        btn_feedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_feedbackMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("E - Commerce");

        jTable1.setModel(model);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(720, 720, 720)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(720, 720, 720)
                .addComponent(btn_feedback))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(249, 249, 249))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btn_logout))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btn_feedback))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    public void populateTable() {
//        String[] columnNames = {"Category","Item","Price","Qty"};
//        Object[][] data = {{"Image.jpg","About"}};
//        DefaultTableModel model = new DefaultTableModel(data, columnNames) {
//
//            private static final long serialVersionUID = 1L;
//            //  Returning the Class of each column will allow different
//            //  renderers to be used based on Class
//
//            @Override
//            public Class getColumnClass(int column) {
//                return getValueAt(0, column).getClass();
//            }
//        };
//        JTable table = new JTable(model);
//        JLabel myLabel = new JLabel("waiting");
//        table.setRowHeight(100);
//        table.setPreferredScrollableViewportSize(table.getPreferredSize());
//        JScrollPane scrollPane = new JScrollPane(table);
//        add(scrollPane, BorderLayout.CENTER);
//        myLabel.setPreferredSize(new Dimension(200, 100));
//        myLabel.setHorizontalAlignment(SwingConstants.CENTER);
//        add(myLabel, BorderLayout.SOUTH);
//        pack();
//    }
    public void getCusername(String str) {
        cusername = str;
    }
    private void btn_feedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_feedbackMouseClicked
        // TODO add your handling code here:
        FeedbackScreen feedback = new FeedbackScreen();
        feedback.setVisible(true);
        feedback.setLocationRelativeTo(null);
        feedback.getCusernameHere(cusername);
        this.dispose();
    }//GEN-LAST:event_btn_feedbackMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Sure? You want to LogOut?", "Alert", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            ChooseScreen choose = new ChooseScreen();
            choose.setVisible(true);
            choose.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        int column = 4; 
        System.out.println(jTable1.getValueAt(row, column));
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_feedback;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
